"ui.background" = { bg = "base" }
"ui.menu" = { fg = "text", bg = "overlay" }
"ui.menu.selected" = { fg = "iris", bg = "surface" }
"ui.linenr" = {fg = "subtle" }
"ui.liner.selected" = "highlightOverlay"
"ui.selection" = { bg = "highlight" }
"comment" = "#6c6c6c"
"ui.cursorline" = { bg = "surface" }
"ui.statusline" = {fg = "foam", bg = "surface" }
"ui.statusline.insert" = {fg = "base", bg = "foam", modifiers = ["bold"]}
"ui.statusline.normal" = {fg = "base", bg = "rose", modifiers = ["bold"]}
"ui.statusline.select" = {fg = "base", bg = "iris", modifiers = ["bold"]}
"ui.statusline.inactive" = { fg = "iris", bg = "surface" }
"ui.cursor" = { fg = "rose", modifiers = ["reversed"] }
"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "foam", modifiers = ["bold"]}
"ui.text.info" = {fg = "pine", modifiers = ["bold"]}
"ui.virtual.whitespace" = "highlight"
"ui.virtual.ruler" = { bg = "surface" }
"operator" = "darkgold"
"variable" = "text"
"constant.numeric" = "green"
"constant" = "text"
"attribute" = "gold" 
"type" = "gold"
"ui.cursor.match" = { fg = "gold", modifiers = ["underlined"] }
"string"  = "green"
"function" = "lightred"
"function.builtin" = "lightred"
"constructor" = "gold"
"special" = "gold"
"keyword" = "pine"
"label" = "iris"
"namespace" = "pine"
"ui.popup" = { bg = "surface" }
"ui.popup.info" = { bg = "surface" }
"ui.window" = { bg = "base" }
"ui.help" = { bg = "overlay", fg = "foam" }
"diff.plus" = "foam"
"diff.delta" = "rose"
"diff.minus" = "love"

"info" = "gold"
"hint" = "gold"
"debug" = "underlined"
"diagnostic" = { modifiers = ["underlined", "italic"] }
"error" = "darkred"

"markup.heading.marker" = "subtle"
"markup.heading.1" = { fg = "love", modifiers = ["bold"] }
"markup.heading.2" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.3" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.4" = { fg = "pine", modifiers = ["bold"] }
"markup.heading.5" = { fg = "foam", modifiers = ["bold"] }
"markup.heading.6" = { fg = "iris", modifiers = ["bold"] }
"markup.list" = { fg = "love" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "iris", modifiers = ["italic"] }
"markup.link.url" = { fg = "pine", modifiers = ["underlined"]}
"markup.link.text" = { fg = "foam" }
"markup.quote" = { fg = "rose" }
"markup.raw" = { fg = "foam" }

[palette]
base     = "#141414" 
surface  = "#1f1d2e" 
overlay  = "#26233a"
inactive = "#555169"
subtle   = "#6e6a86"
text     = "#beab94"
love     = "#eb6f92"
gold     = "#f6c177"
darkgold = "#f4b052"
rose     = "#ebbcba"
pine     = "#5ba8c7"
foam     = "#9ccfd8"
iris     = "#c4a7e7"
highlight = "#2a2837"
highlightInactive = "#211f2d"
highlightOverlay = "#3a384a"
green = "#5abba0"
lightred = "#c97461"
darkred = "#a44c38"
