theme = "sonokai"

[editor]
auto-info = false
cursorline = true
gutters = ["diagnostics", "line-numbers"]
line-number = "relative"
mouse = false
true-color = true

[editor.lsp]
display-messages = true

[keys.normal]
"$" = "goto_line_end"
"0" = "goto_line_start"

